
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from turtle import title


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

EditStatusWindow = Tk()

class Edit_Status_window():

    def __init__(self):
        self.EditStatusWindow=EditStatusWindow
        self.interface()
        self.generate_Edit_Status_window()

    def interface(self):

        self.EditStatusWindow.geometry("521x133")
        self.EditStatusWindow.configure(bg = "#2C0A59")
        self.EditStatusWindow.title("Edit Status")

        self.canvas = Canvas(
            self.EditStatusWindow,
            bg = "#2C0A59",
            height = 133,
            width = 521,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        self.canvas.place(x = 0, y = 0)

        self.EditStatusWindow.btn_inactive2Read = PhotoImage(file=relative_to_assets("button_2Read.png"))
        self.EditStatusWindow.btn_active2Read = PhotoImage(file=relative_to_assets("button_2ReadActive.png"))

        self.button_image_2Read = PhotoImage(
            file=relative_to_assets("button_2Read.png"))

        self.button_2Read = Button(
            image=self.button_image_2Read,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_2Read clicked"),
            bg = "#2C0A59",
            activebackground="#2C0A59",
            relief="sunken",
            cursor="hand2"
        )
        self.button_2Read.place(
            x=10.0,
            y=57.0,

        )

        self.button_2Read.bind("<Enter>", lambda e: self.button_2Read.config(image=self.EditStatusWindow.btn_active2Read))
        self.button_2Read.bind("<Leave>", lambda e: self.button_2Read.config(image=self.EditStatusWindow.btn_inactive2Read))

        self.EditStatusWindow.btn_inactive2Reading = PhotoImage(file=relative_to_assets("button_2Reading.png"))
        self.EditStatusWindow.btn_active2Reading = PhotoImage(file=relative_to_assets("button_2ReadingActive.png"))

        self.button_image_2Reading = PhotoImage(
            file=relative_to_assets("button_2Reading.png"))
        self.button_2Reading = Button(
            image=self.button_image_2Reading,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_2Reading clicked"),
            bg = "#2C0A59",
            activebackground="#2C0A59",
            relief="sunken",
            cursor="hand2"
        )
        self.button_2Reading.place(
            x=175.0,
            y=58.0,

        )
        self.button_2Reading.bind("<Enter>", lambda e: self.button_2Reading.config(image=self.EditStatusWindow.btn_active2Reading))
        self.button_2Reading.bind("<Leave>", lambda e: self.button_2Reading.config(image=self.EditStatusWindow.btn_inactive2Reading))

        self.EditStatusWindow.btn_inactive2IWTR = PhotoImage(file=relative_to_assets("button_2IWTR.png"))
        self.EditStatusWindow.btn_active2IWTR = PhotoImage(file=relative_to_assets("button_2IWTRActive.png"))

        self.button_image_2IWTR = PhotoImage(
            file=relative_to_assets("button_2IWTR.png"))
        self.button_2IWTR = Button(
            image=self.button_image_2IWTR,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_2IWTR clicked"),
            bg = "#2C0A59",
            activebackground="#2C0A59",
            relief="sunken",
            cursor="hand2"
        )
        self.button_2IWTR.place(
            x=345,
            y=59.0,

        )

        self.button_2IWTR.bind("<Enter>", lambda e: self.button_2IWTR.config(image=self.EditStatusWindow.btn_active2IWTR))
        self.button_2IWTR.bind("<Leave>", lambda e: self.button_2IWTR.config(image=self.EditStatusWindow.btn_inactive2IWTR))

        self.image_image_Editstatus = PhotoImage(
            file=relative_to_assets("image_EditStatus.png"))
        self.image_Editstatus = self.canvas.create_image(
            115.466064453125,
            29.375,
            image=self.image_image_Editstatus
        )

    def generate_Edit_Status_window(self):
        self.EditStatusWindow.resizable(False, False)
        self.EditStatusWindow.mainloop()

Edit_Status_window()