
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

class MyBooksWindow:
    
    def __init__(self):
        self.my_books_window = Tk()

        self.my_books_window.geometry("1300x700")
        self.my_books_window.configure(bg = "#2C0A59")
        self.my_books_window.maxsize(width=1300, height=700)#configura as dmensoes maximas da tela
        self.my_books_window.minsize(width=400, height=170)

    def back_to_home(self):
        from interface.screens.HomeWindow import HomeWindow
        self.my_books_window.destroy()
        self.novaHome = HomeWindow()
        self.novaHome.generate_home_window()

    def generate_my_books_window(self):
        canvas = Canvas(
            self.my_books_window,
            self.my_books_window.title("Mybooks"),
            bg = "#2C0A59",
            height = 700,
            width = 1297,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        button_image_icon = PhotoImage(
            file=relative_to_assets("icon.png"))

        button_icon = Button(
            image=button_image_icon,
            borderwidth=0,
            highlightthickness=0,
            relief="flat",
            bg="#2C0A59",
            bd=0,
            activebackground="#2C0A60",
            command=self.back_to_home,
            cursor="hand2",
        )

        button_icon.place(
            x=1194.0,
            y=19.0,
        )

        image_image_MyBooks = PhotoImage(
            file=relative_to_assets("MyBooks.png"))
        image_1 = canvas.create_image(
            248.861328125,
            68.0,
            image=image_image_MyBooks
        )
        self.my_books_window.resizable(False, False)
        self.my_books_window.mainloop()