
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, font


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1300x700")
window.configure(bg = "#2C0A59")


canvas = Canvas(
    window,
    bg = "#2C0A59",
    height = 700,
    width = 1300,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="sunken",
    bd=0,
    bg="#2C0A59",
    activebackground="#2C0A59",
    cursor="hand2",
)
button_1.place(
    x=1197.0,
    y=19.0,
    width=71.0,
    height=86.0
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    339.0,
    59.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    151.0,
    129.0,
    image=image_image_2
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    207.5,
    180.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#93679A",
    highlightthickness=0,
    justify="center",
    font=('Georgia 20')
)
entry_1.place(
    x=65.5,
    y=161.5,
    width=284.0,
    height=30.75,
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="sunken",
    cursor="hand2",
    activebackground="#2C0A59",
    bg="#2C0A59",
    bd=0,   
)
button_2.place(
    x=386.0,
    y=162.0,
    width=40.3193359375,
    height=37.80328369140625
)
window.resizable(False, False)
window.mainloop()
